### ISSUE TITLE
v0.3 Feedback

### ISSUE THREAD

**Issue by nirandiw** [CS2103AUG2016-T10-C2/main#125]
# Issue Management
- The issue I reported #87   was not assigned to anyone and it does not have a milestone.  It is always nice to do these things so that you can track everything faster.
# Developer Guide
- I see that the web component is removed from the Architecture. Curious to know how does your `help` command work? Is it not linked to the github page?
- Take note of the way your interfaces are placed in diagrams compared to the five diagrams. In the given diagrams their position is rarely intuitive to understand the data flow. When drawing diagrams try to do it like that. It is a minor comment. 
-  You can include a few of the following to improve the developer guide
  Add Classes related to new features you have implemented
  Compare with alternative designs if possible
  Add more description e.g. show at least one interaction (sequence diagram) within each component
  Use object diagrams to show the object structure at runtime
  Can use activity diagrams and OO domains where applicable.
  Explain how undo/redo was implemented if you do it.
# User Guide
- This is in good shape right now. The command summary section will be used heavily by our testers. So make it as easy to use as possible. e.g. give examples for each command. Make sure the list is comprehensive.

**Comment by kabir-plod** [comment]
## Issue Management

- Noted.

## Developer Guide

- `help` command opens a pop up browser window showing the github page. The user guide is not shown in the main app window.

- Noted.

- Noted.

## User Guide

- Noted, thanks!
